# Generated by Django 3.1.3 on 2021-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
