# Generated by Django 3.1.3 on 2020-11-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savemart', '0002_auto_20201127_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Shop',
            new_name='ProductShop',
        ),
    ]
